name: Stunnel Setup

on:
  push:
    branches:
      - main

jobs:
  setup-stunnel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install stunnel
      run: |
        sudo apt-get update
        sudo apt-get install -y stunnel4

    - name: Create stunnel configuration file
      run: |
        cat > stunnel.conf <<EOF
        pid=/var/run/stunnel.pid
        cert=/etc/stunnel/stunnel.pem

        [ssh]
        accept=443
        connect=127.0.0.1:22
        EOF

    - name: Move stunnel configuration to /etc/stunnel
      run: |
        sudo mv stunnel.conf /etc/stunnel/stunnel.conf

    - name : prin IP
      run: |
          sudo ifconfig

    - name: Restart stunnel service
      run: |
        systemctl status stunnel4.service
        journalctl -xeu stunnel4.service

        cat /etc/stunnel/stunnel.conf




    
