name: Stunnel Setup

on:
  push:
    branches:
      - main

jobs:
  setup-stunnel:
    runs-on: ubuntu-latest

    env:
      PROXY_ADDRESS: ${{ secrets.PROXY_ADDRESS }}
      PROXY_USERNAME: ${{ secrets.PROXY_USERNAME }}
      PROXY_PASSWORD: ${{ secrets.PROXY_PASSWORD }}
      JUMP_HOST_ADDRESS: ${{ secrets.JUMP_HOST_ADDRESS }}
      JUMP_HOST_DNS_NAME: ${{ secrets.JUMP_HOST_DNS_NAME }}

    steps:
    - name: Print values
      run: |
        echo "Proxy Address: $PROXY_ADDRESS"
        echo "Proxy Username: $PROXY_USERNAME"
        echo "Proxy Password: $PROXY_PASSWORD"
        echo "Jump Host Address: $JUMP_HOST_ADDRESS"
        echo "Jump Host DNS Name: $JUMP_HOST_DNS_NAME"

    - name: Install stunnel
      run: |
        sudo apt-get update
        sudo apt-get install -y stunnel4

    - name: Create stunnel configuration file
      run: |
        cat > stunnel.conf <<EOF
        pid=/var/run/stunnel.pid
        cert=/etc/stunnel/stunnel.pem

        [ssh]
        client=yes
        libwrap=no
        accept=2222
        connect=$PROXY_ADDRESS
        protocolUsername=$PROXY_USERNAME
        protocolPassword=$PROXY_PASSWORD
        protocolHost=$JUMP_HOST_ADDRESS:443
        EOF

    - name: Move stunnel configuration to /etc/stunnel
      run: |
        sudo mv stunnel.conf /etc/stunnel/stunnel.conf

    - name: Restart stunnel service
      run: |
        sudo systemctl restart stunnel4
