name: Setup and Configure Stunnel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Server and Install Stunnel
      run: |
        # Install stunnel on the server
        ssh <your-server-username>@<your-server-ip> 'sudo apt-get update && sudo apt-get install -y stunnel'

    - name: Configure Stunnel
      run: |
        # Upload stunnel configuration file to the server
        scp .github/stunnel/stunnel.conf <your-server-username>@<your-server-ip>:/tmp/
        # SSH to the server and move the configuration to the correct location
        ssh <your-server-username>@<your-server-ip> 'sudo mv /tmp/stunnel.conf /etc/stunnel/stunnel.conf'

    - name: Restart Stunnel
      run: |
        # Restart stunnel on the server
        ssh <your-server-username>@<your-server-ip> 'sudo service stunnel4 restart'
